### ISSUE TITLE
sentencepiece special cases aren't loaded properly?

### ISSUE THREAD

**Issue by Vijayabhaskar96** [goru001/nlp-for-tamil#2]
I'm looking at [Tamil_Language_Model_ULMFiT.ipynb](https://github.com/goru001/nlp-for-tamil/blob/master/language-model/Tamil_Language_Model_ULMFiT.ipynb) in the cell [9] from `tokenizer.special_cases` it is clear that fastai tokens are included as sentencepiece special cases, but in cell [18] when you print `data_lm.show_batch()` the fourth sample you see `<unk>` (sentencepiece default token) instead of `xxunk` (fastai token) and also in cell[24]: `!head -50 tamil_spm_8k.vocab` you don't see any fastai special tokens. Why is that? bug?

**Comment by goru001** [comment]
@Vijayabhaskar96 Thanks for reaching out. [ "unk" is "unknown" token for sentencepiece](https://github.com/google/sentencepiece#redefine-special-meta-tokens), "xxunk" is "unknown" token for fastai, so, you won't find "xxunk" in  `tamil_spm_8k.vocab`. 

As far as seeing <unk> in `data_lm.show_batch()` is concerned, this is known and [this was an issue with sentencepiece](https://github.com/google/sentencepiece/issues/255) at the time when I had trained initial models. The repercussion of this issue is we ended up having two tokens unk and xxunk for unknown. This shouldn't be a big concern as far as model usage and performance is concerned, and hence I'd parked to resolve this issue for the future [until fastai v2 is released with sentencepiece integration](https://forums.fast.ai/t/adding-sentencepiecetokenizer-to-fastai-text-data/29864/15?u=disisbig). Let me know if you see any serious concerns with this issue and I can prioritize fixing this.
